version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: reposensei-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./reposensei-backend
    container_name: reposensei-backend
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - PYTHON_BACKEND_URL=${PYTHON_BACKEND_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - mongodb
      - python-backend
    restart: unless-stopped

  python-backend:
    build:
      context: ./reposensei-python-backend
    container_name: reposensei-python-backend
    ports:
      - '5005:5005'
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./reposensei-frontend
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        VITE_BACKEND_URL: ${BACKEND_URL}
    container_name: reposensei-frontend
    ports:
      - '5173:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
